apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "harbor-scanner-kubescape.fullname" . }}
  labels:
    {{- include "harbor-scanner-kubescape.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "harbor-scanner-kubescape.fullname" . }}
  labels:
    {{- include "harbor-scanner-kubescape.labels" . | nindent 4 }}
rules:
  # Read VulnerabilityManifest CRDs from kubescape/storage
  - apiGroups:
      - spdx.softwarecomposition.kubescape.io
    resources:
      - vulnerabilitymanifests
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "harbor-scanner-kubescape.fullname" . }}
  labels:
    {{- include "harbor-scanner-kubescape.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "harbor-scanner-kubescape.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "harbor-scanner-kubescape.fullname" . }}
    namespace: {{ .Release.Namespace }}
